import 'dart:ui';

import 'package:flutter/material.dart';

double pdfFontSize = 8;

double modalPurchasesWidth = 500;

double modalSalesWidth = 500;

double kDefaultPadding = 20;

double kxDefaultFontSize = 20;

double kFontSize = 17;

List<String> adminPermissions = [
  "ALLOW_VIEW_USERS_SCREEN",
  "ALLOW_ADD_COMPANY_PLATFORM",
  "ALLOW_DELETE_COMPANY_PLATFORM",
  "ALLOW_ADD_PURCHASE_INVOICE",
  "ALLOW_UPDATE_PURCHASE_INVOICE",
  "ALLOW_DELETE_PURCHASE_INVOICE",
  "ALLOW_MOVE_PURCHASE_INVOICE",
  "ALLOW_ADD_SALE_INVOICE",
  "ALLOW_UPDATE_SALE_INVOICE",
  "ALLOW_DELETE_SALE_INVOICE",
  "ALLOW_MOVE_SALE_INVOICE",
  "ALLOW_ADD_OVERRIDE_INVOICE",
  "ALLOW_UPDATE_OVERRIDE_INVOICE",
  "ALLOW_DELETE_OVERRIDE_INVOICE",
  "ALLOW_MOVE_OVERRIDE_INVOICE",
  "ALLOW_VIEW_COMPANY_PLATFORM_VISIBILITY_CONTROLLER"
];

List<String> editorPermissions = [
  "ALLOW_ADD_COMPANY_PLATFORM",
  "ALLOW_ADD_PURCHASE_INVOICE",
  "ALLOW_UPDATE_PURCHASE_INVOICE",
  "ALLOW_DELETE_PURCHASE_INVOICE",
  "ALLOW_MOVE_PURCHASE_INVOICE",
  "ALLOW_ADD_SALE_INVOICE",
  "ALLOW_UPDATE_SALE_INVOICE",
  "ALLOW_DELETE_SALE_INVOICE",
  "ALLOW_MOVE_SALE_INVOICE",
  "ALLOW_ADD_OVERRIDE_INVOICE",
  "ALLOW_UPDATE_OVERRIDE_INVOICE",
  "ALLOW_DELETE_OVERRIDE_INVOICE",
  "ALLOW_MOVE_OVERRIDE_INVOICE"
];


const kWindowBorderColor =  Color(0xFF393838);

const kPrimaryColor = Colors.blue;

const kErrorColor =  Color(0xFFFA473B);